[package]
name = "bibextracter"
version = "0.1.0"
edition = "2021"
author = "Luc Blassel"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex =  "1"
biblatex = "0.6"
clap = { version = "4.0", features = ["derive"]}